spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ${KAFKA_CONSUMER_GROUP_ID:minha-aplicacao}
      auto-offset-reset: ${KAFKA_AUTO-OFFSET-RESET:latest}
    topic.transactions: ${KAFKA_TOPIC_TRANSACTIONS:transacoes}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/transaction?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update

  security.oauth2.resourceserver.jwt:
    issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/auth/realms/proposta}
    jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:18080/auth/realms/proposta/protocol/openid-connect/certs}

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: info,metrics,health
  endpoint:
    health:
      probes:
        enabled: true